### ISSUE TITLE
Name files d'nt appear on the left

### ISSUE THREAD

**Issue by photoju** [thibaud-rohmer/PhotoShow#268]
With plublic connect on the site, the names on the left do not appear.
Then I cannot go back on another galerie.
But if I put a private login this good, all names appear
May be I do something wrong but what ?
This is here : martine.defeuillas.free.fre
![photo](https://cloud.githubusercontent.com/assets/3889372/5816240/7c38176e-a09e-11e4-955c-f50b431df786.jpg)
![galeries](https://cloud.githubusercontent.com/assets/3889372/5816244/88635b34-a09e-11e4-80d9-355f7d871397.jpg)

**Comment by thibaud-rohmer** [comment]
Try logging in as admin, and going to the root folder. I'm guessing that
folder is in private: change it to public.

**Comment by photoju** [comment]
No Its in public mode, nothing until Iam logged
![public mode](https://cloud.githubusercontent.com/assets/3889372/5820283/3dd451f6-a0c4-11e4-8a93-46b213ce233e.jpg)
Once logged in "Admin" or simple use
![admin](https://cloud.githubusercontent.com/assets/3889372/5820315/6aa92c06-a0c4-11e4-9ce3-59ce8578fa14.jpg)

**Comment by photoju** [comment]
If you can said me where I mut look for, Itry to correct

**Comment by thibaud-rohmer** [comment]
1. log in as admin
2. click on the left on "photos"
3. on the right, in "access", i'm guessing it's red. Click it.
4. profit.

**Comment by photoju** [comment]
Yes very well, I did not understand this
Thank you and sorry for my mistake !!
I thought clic on Gallery was enough

**Comment by thibaud-rohmer** [comment]
No worries :) enjoy !
