### ISSUE TITLE
Nginx installation not displaying pictures

### ISSUE THREAD

**Issue by saintger** [thibaud-rohmer/PhotoShow#275]
Hello,

I tried to install Photoshow with Nginx using the Docker file as example and it seems that the files cannot be displayed.

Here is the nginx configuration:

    upstream php5-fpm-sock {
	server unix:/var/run/php5-fpm.sock;
    }

    server {
	listen 80;
	server_name example.com;
	rewrite ^ https://$http_host$request_uri? permanent;
    }

    server {
	listen 443 ssl;
	ssl_certificate     /etc/ssl/localcerts/example.com.pem;
	ssl_certificate_key /etc/ssl/localcerts/example.com.key;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:5m;
	ssl_dhparam /etc/ssl/localcerts/dhparam.pem;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
	ssl_prefer_server_ciphers on;
	add_header Strict-Transport-Security max-age=15768000;

	add_header X-Frame-Options DENY;
	add_header X-Content-Type-Options nosniff;

	server_name ;
	location / {
	    fastcgi_param   HTTPS               on;
	    fastcgi_param   HTTP_SCHEME         https;

	    access_log      /var/log/nginx/photoshow.access.log;
	    error_log       /var/log/nginx/photoshow.error.log;

	    alias /var/www/PhotoShow/;
	    index index.php;
	    client_max_body_size 0;
	    location ~* \.php$ {
	        allow all;
	        include fastcgi_params;
	        fastcgi_pass php5-fpm-sock;
	        fastcgi_param SCRIPT_FILENAME /var/www/PhotoShow/$fastcgi_script_name;
	        fastcgi_param QUERY_STRING $query_string;
	        fastcgi_intercept_errors off;
            }
        }
    }

And here is the log when I try to upload and display a picture:

    2015/03/29 17:05:55 [error] 1902#0: *1 open() "/var/www/PhotoShow/undefined&j=Pan" failed (2: No such file or directory), client: xx.xxx.xxx.xx, server: xxx.xx.xxx.xx, request: "GET /undefined&j=Pan HTTP/1.1", host: "xxx.xx.xxx.xx", referrer: "https://example.com/?f=Demo"

I don't any other error message, so I don't understand what is this "undefined" URL which appears in the log ?

**Comment by thibaud-rohmer** [comment]
Hi,

I think you' re missing this after "include fastcgi_params;" :

fastcgi_index index.php;


(the "undefined" comes from $fastcgi_script_name that uses fastcgi_index,
which is not defined).

**Comment by saintger** [comment]
Hello,

Indeed that was the mistake.
I copy-pasted what I found in the Docker directory and this line was in comment.

Thanks !
