### ISSUE TITLE
Website cannot load 

### ISSUE THREAD

**Issue by romainallain** [thibaud-rohmer/PhotoShow#330]
PHP message: PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in Settings.php on line 150

**Comment by gboudreau** [comment]
What version of PHP are you using?
What if you replace line 150 of Settings.php:

    static public $cache_max_age = 14*24*60*60;

with this:

    static public $cache_max_age = 1209600;

**Comment by gboudreau** [comment]
Looks like PHP 5.6 is required for static expressions, which you don't have.

I would strongly advise to update your PHP version, as anything lower than 5.6 is not supported anymore by PHP, meaning you will not get security patches.

But in all cases, making the change I suggested above will fix your problem.

**Comment by romainallain** [comment]
$ php --version
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

If I replace `static public $cache_max_age = 14*24*60*60;` with your suggestion, it works.
