### ISSUE TITLE
Thumbnails not being generated

### ISSUE THREAD

**Issue by beeurd** [thibaud-rohmer/PhotoShow#345]
I'll be honest here, it's most likely me just missing something but no matter what I try I can't get thumbnails to generate.

I'm using php7 and have both gd and imagick enabled. 
I've checked folder permissions are okay - I can that the folders are created for the thumbs, and a  .rights.xml folder seems to be generated inside each one.

Anything obvious I might have missed?

**Comment by thibaud-rohmer** [comment]
Seeing as you have gd and imagemagick, I'd definitely point you towards the
folder permissions, but you've already checked that.

You know that thumbnails generate only when you visit the page, I guess ?
(meaning that photos of folder Toto will get their thumbs generated when
you visit the folder Toto on your website).

**Comment by beeurd** [comment]
Wasn't expecting a reply that fast, you are far too efficient! xD

It is working now - it seems I have to use full paths rather than relative paths in the config file. I don't know why I didn't try that before to be honest. It's all good now :)

**Comment by thibaud-rohmer** [comment]
Haha I usually don't respond that fast (or don't respond at all :/ ), you
just got lucky ;) glad your issue got resolved

**Comment by viennaa** [comment]
This should be pinned. I am using this gallery since quite a while and everyone complained about loading times of the previews until I figured out, there are no thumbs in my thumbnail folder. Also had the path relative in the config and this pointed me in the right direction. Thanks!

**Comment by thibaud-rohmer** [comment]
I think the best would be to have a notification in the UI saying that the
thumbnails displayed are, in fact, not thumbnails.
